/**
 * Auto-generated by scripts/download-assets.js
 * Do not edit manually - re-run script to update
 * 
 * Asset mappings for Valorant agents and maps
 */

import { normalizeAssetName } from './normalizeAssetName';

export const agentAssets = {
  astra: "/assets/agents/astra.webp",
  breach: "/assets/agents/breach.webp",
  brimstone: "/assets/agents/brimstone.webp",
  chamber: "/assets/agents/chamber.webp",
  clove: "/assets/agents/clove.webp",
  cypher: "/assets/agents/cypher.webp",
  deadlock: "/assets/agents/deadlock.webp",
  fade: "/assets/agents/fade.webp",
  gekko: "/assets/agents/gekko.webp",
  harbor: "/assets/agents/harbor.webp",
  iso: "/assets/agents/iso.webp",
  jett: "/assets/agents/jett.webp",
  kayo: "/assets/agents/kayo.webp",
  killjoy: "/assets/agents/killjoy.webp",
  miks: "/assets/agents/miks.webp",
  neon: "/assets/agents/neon.webp",
  omen: "/assets/agents/omen.webp",
  phoenix: "/assets/agents/phoenix.webp",
  raze: "/assets/agents/raze.webp",
  reyna: "/assets/agents/reyna.webp",
  sage: "/assets/agents/sage.webp",
  skye: "/assets/agents/skye.webp",
  sova: "/assets/agents/sova.webp",
  tejo: "/assets/agents/tejo.webp",
  veto: "/assets/agents/veto.webp",
  viper: "/assets/agents/viper.webp",
  vyse: "/assets/agents/vyse.webp",
  waylay: "/assets/agents/waylay.webp",
  yoru: "/assets/agents/yoru.webp"
};

export const mapAssets = {
  abyss: "/assets/maps/abyss.webp",
  ascent: "/assets/maps/ascent.webp",
  basictraining: "/assets/maps/basictraining.webp",
  bind: "/assets/maps/bind.webp",
  breeze: "/assets/maps/breeze.webp",
  corrode: "/assets/maps/corrode.webp",
  district: "/assets/maps/district.webp",
  drift: "/assets/maps/drift.webp",
  fracture: "/assets/maps/fracture.webp",
  glitch: "/assets/maps/glitch.webp",
  haven: "/assets/maps/haven.webp",
  icebox: "/assets/maps/icebox.webp",
  kasbah: "/assets/maps/kasbah.webp",
  lotus: "/assets/maps/lotus.webp",
  pearl: "/assets/maps/pearl.webp",
  piazza: "/assets/maps/piazza.webp",
  skirmisha: "/assets/maps/skirmisha.webp",
  skirmishb: "/assets/maps/skirmishb.webp",
  skirmishc: "/assets/maps/skirmishc.webp",
  split: "/assets/maps/split.webp",
  sunset: "/assets/maps/sunset.webp",
  therange: "/assets/maps/therange.webp"
};

/**
 * Get agent asset path by agent name
 * @param {string} agentName - Agent name (any case/format)
 * @returns {string|null} Asset path or null if not found
 */
export function getAgentAsset(agentName) {
  if (!agentName) return null;
  const normalized = normalizeAssetName(agentName);
  return agentAssets[normalized] || null;
}

/**
 * Get map asset path by map name
 * @param {string} mapName - Map name (any case/format)
 * @returns {string|null} Asset path or null if not found
 */
export function getMapAsset(mapName) {
  if (!mapName) return null;
  const normalized = normalizeAssetName(mapName);
  return mapAssets[normalized] || null;
}
