/**
 * Auto-generated by scripts/download-assets.js
 * Do not edit manually - re-run script to update
 * 
 * Asset mappings for Valorant agents and maps
 */

import { normalizeAssetName } from './normalizeAssetName';

export const agentAssets = {
  astra: "/assets/agents/astra.png",
  breach: "/assets/agents/breach.png",
  brimstone: "/assets/agents/brimstone.png",
  chamber: "/assets/agents/chamber.png",
  clove: "/assets/agents/clove.png",
  cypher: "/assets/agents/cypher.png",
  deadlock: "/assets/agents/deadlock.png",
  fade: "/assets/agents/fade.png",
  gekko: "/assets/agents/gekko.png",
  harbor: "/assets/agents/harbor.png",
  iso: "/assets/agents/iso.png",
  jett: "/assets/agents/jett.png",
  kayo: "/assets/agents/kayo.png",
  killjoy: "/assets/agents/killjoy.png",
  miks: "/assets/agents/miks.png",
  neon: "/assets/agents/neon.png",
  omen: "/assets/agents/omen.png",
  phoenix: "/assets/agents/phoenix.png",
  raze: "/assets/agents/raze.png",
  reyna: "/assets/agents/reyna.png",
  sage: "/assets/agents/sage.png",
  skye: "/assets/agents/skye.png",
  sova: "/assets/agents/sova.png",
  tejo: "/assets/agents/tejo.png",
  veto: "/assets/agents/veto.png",
  viper: "/assets/agents/viper.png",
  vyse: "/assets/agents/vyse.png",
  waylay: "/assets/agents/waylay.png",
  yoru: "/assets/agents/yoru.png"
};

export const mapAssets = {
  abyss: "/assets/maps/abyss.webp",
  ascent: "/assets/maps/ascent.webp",
  basictraining: "/assets/maps/basictraining.webp",
  bind: "/assets/maps/bind.webp",
  breeze: "/assets/maps/breeze.webp",
  corrode: "/assets/maps/corrode.webp",
  district: "/assets/maps/district.webp",
  drift: "/assets/maps/drift.webp",
  fracture: "/assets/maps/fracture.webp",
  glitch: "/assets/maps/glitch.webp",
  haven: "/assets/maps/haven.webp",
  icebox: "/assets/maps/icebox.webp",
  kasbah: "/assets/maps/kasbah.webp",
  lotus: "/assets/maps/lotus.webp",
  pearl: "/assets/maps/pearl.webp",
  piazza: "/assets/maps/piazza.webp",
  split: "/assets/maps/split.webp",
  sunset: "/assets/maps/sunset.webp",
  therange: "/assets/maps/therange.webp"
};

/**
 * Get agent asset path by agent name
 * @param {string} agentName - Agent name (any case/format)
 * @returns {string|null} Asset path or null if not found
 */
export function getAgentAsset(agentName) {
  if (!agentName) return null;
  const normalized = normalizeAssetName(agentName);
  return agentAssets[normalized] || null;
}

/**
 * Get map asset path by map name
 * @param {string} mapName - Map name (any case/format)
 * @returns {string|null} Asset path or null if not found
 */
export function getMapAsset(mapName) {
  if (!mapName) return null;
  const normalized = normalizeAssetName(mapName);
  return mapAssets[normalized] || null;
}
