/**
 * Auto-generated by scripts/download-ranks.js
 * Do not edit manually - re-run script to update
 * 
 * Asset mappings for Valorant competitive tier (rank) icons
 */

export const rankAssets = {
  unranked: "/ranks/unranked.png",
  iron1: "/ranks/iron1.png",
  iron2: "/ranks/iron2.png",
  iron3: "/ranks/iron3.png",
  bronze1: "/ranks/bronze1.png",
  bronze2: "/ranks/bronze2.png",
  bronze3: "/ranks/bronze3.png",
  silver1: "/ranks/silver1.png",
  silver2: "/ranks/silver2.png",
  silver3: "/ranks/silver3.png",
  gold1: "/ranks/gold1.png",
  gold2: "/ranks/gold2.png",
  gold3: "/ranks/gold3.png",
  platinum1: "/ranks/platinum1.png",
  platinum2: "/ranks/platinum2.png",
  platinum3: "/ranks/platinum3.png",
  diamond1: "/ranks/diamond1.png",
  diamond2: "/ranks/diamond2.png",
  diamond3: "/ranks/diamond3.png",
  ascendant1: "/ranks/ascendant1.png",
  ascendant2: "/ranks/ascendant2.png",
  ascendant3: "/ranks/ascendant3.png",
  immortal1: "/ranks/immortal1.png",
  immortal2: "/ranks/immortal2.png",
  immortal3: "/ranks/immortal3.png",
  radiant: "/ranks/radiant.png"
};

/**
 * Normalize rank/tier name for lookup
 * Examples:
 *   "Iron 1" → "iron1"
 *   "GOLD 3" → "gold3"
 *   "Radiant" → "radiant"
 *   "Unranked" → "unranked"
 */
export function normalizeRankName(tierName) {
  if (!tierName) return null;
  return tierName
    .toLowerCase()
    .replace(/\s+/g, '')
    .replace(/[^a-z0-9]/g, '');
}

/**
 * Get rank asset path by tier name
 * @param {string} tierName - Rank tier name (any case/format)
 * @returns {string|null} Asset path or null if not found
 */
export function getRankAsset(tierName) {
  if (!tierName) return null;
  const normalized = normalizeRankName(tierName);
  return rankAssets[normalized] || null;
}
