/**
 * Download Valorant competitive tier (rank) icons from valorant-api.com
 * 
 * This script:
 * 1. Fetches competitive tier data from Valorant API
 * 2. Downloads rank icons locally to public/ranks/
 * 3. Auto-generates lib/rankMappings.js with asset paths
 * 
 * Usage: npm run download:ranks
 */

const https = require('https');
const fs = require('fs');
const path = require('path');

// Normalize rank name to lowercase without spaces
function normalizeRankName(name) {
  if (!name) return 'unknown';
  return name
    .toLowerCase()
    .replace(/\s+/g, '')         // Remove spaces: "IRON 1" → "iron1"
    .replace(/[^a-z0-9]/g, '');  // Remove special chars
}

const ROOT_DIR = path.join(__dirname, '..');
const RANKS_DIR = path.join(ROOT_DIR, 'public', 'ranks');
const MAPPINGS_FILE = path.join(ROOT_DIR, 'lib', 'rankMappings.js');

const COMPETITIVE_TIERS_API = 'https://valorant-api.com/v1/competitivetiers';

// Create directory if it doesn't exist
function ensureDir(dir) {
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
    console.log(`✓ Created directory: ${dir}`);
  }
}

// Fetch JSON from URL
function fetchJSON(url) {
  return new Promise((resolve, reject) => {
    https.get(url, (res) => {
      let data = '';
      res.on('data', (chunk) => data += chunk);
      res.on('end', () => {
        try {
          resolve(JSON.parse(data));
        } catch (err) {
          reject(err);
        }
      });
    }).on('error', reject);
  });
}

// Download file from URL
function downloadFile(url, filePath) {
  return new Promise((resolve, reject) => {
    const file = fs.createWriteStream(filePath);
    https.get(url, (res) => {
      res.pipe(file);
      file.on('finish', () => {
        file.close();
        resolve();
      });
    }).on('error', (err) => {
      fs.unlink(filePath, () => {}); // Delete partial file
      reject(err);
    });
  });
}

// Download rank icons
async function downloadRanks() {
  console.log('\n📥 Fetching competitive tiers from Valorant API...');
  
  try {
    const response = await fetchJSON(COMPETITIVE_TIERS_API);
    const allSeasons = response.data;
    
    // Use the LAST season (most recent - Episode 5)
    const latestSeason = allSeasons[allSeasons.length - 1];
    console.log(`✓ Using latest season: ${latestSeason.assetObjectName}`);
    console.log(`  UUID: ${latestSeason.uuid}`);
    console.log(`  Tiers: ${latestSeason.tiers.length}`);
    
    const tiers = latestSeason.tiers;
    const rankMappings = {};
    let downloadCount = 0;
    let skipCount = 0;
    
    for (const tier of tiers) {
      const { tier: tierNum, tierName, smallIcon } = tier;
      
      // Skip tiers with no icon (tiers 1-2 are unused)
      if (!smallIcon) {
        console.log(`  ⊘ Skipping tier ${tierNum}: ${tierName || 'unnamed'} (no icon)`);
        skipCount++;
        continue;
      }
      
      const normalizedName = normalizeRankName(tierName);
      const fileName = `${normalizedName}.png`;
      const filePath = path.join(RANKS_DIR, fileName);
      
      try {
        await downloadFile(smallIcon, filePath);
        rankMappings[normalizedName] = `/ranks/${fileName}`;
        console.log(`  ✓ Downloaded: ${tierName} (tier ${tierNum}) → ${fileName}`);
        downloadCount++;
      } catch (err) {
        console.error(`  ✗ Failed to download ${tierName}:`, err.message);
      }
    }
    
    console.log(`\n✓ Downloaded ${downloadCount} rank icons (skipped ${skipCount})`);
    return rankMappings;
    
  } catch (err) {
    console.error('✗ Error fetching competitive tiers:', err);
    throw err;
  }
}

// Generate rankMappings.js file
function generateMappingsFile(rankMappings) {
  console.log('\n📝 Generating rank mappings file...');
  
  // Sort entries for consistent output
  const sortedEntries = Object.entries(rankMappings).sort((a, b) => {
    // Custom sort order: unranked first, then by rank tier
    const rankOrder = [
      'unranked',
      'iron1', 'iron2', 'iron3',
      'bronze1', 'bronze2', 'bronze3',
      'silver1', 'silver2', 'silver3',
      'gold1', 'gold2', 'gold3',
      'platinum1', 'platinum2', 'platinum3',
      'diamond1', 'diamond2', 'diamond3',
      'ascendant1', 'ascendant2', 'ascendant3',
      'immortal1', 'immortal2', 'immortal3',
      'radiant'
    ];
    const aIndex = rankOrder.indexOf(a[0]);
    const bIndex = rankOrder.indexOf(b[0]);
    if (aIndex === -1 && bIndex === -1) return a[0].localeCompare(b[0]);
    if (aIndex === -1) return 1;
    if (bIndex === -1) return -1;
    return aIndex - bIndex;
  });
  
  const rankEntries = sortedEntries
    .map(([key, value]) => `  ${key}: "${value}"`)
    .join(',\n');
  
  const content = `/**
 * Auto-generated by scripts/download-ranks.js
 * Do not edit manually - re-run script to update
 * 
 * Asset mappings for Valorant competitive tier (rank) icons
 */

export const rankAssets = {
${rankEntries}
};

/**
 * Normalize rank/tier name for lookup
 * Examples:
 *   "Iron 1" → "iron1"
 *   "GOLD 3" → "gold3"
 *   "Radiant" → "radiant"
 *   "Unranked" → "unranked"
 */
export function normalizeRankName(tierName) {
  if (!tierName) return null;
  return tierName
    .toLowerCase()
    .replace(/\\s+/g, '')
    .replace(/[^a-z0-9]/g, '');
}

/**
 * Get rank asset path by tier name
 * @param {string} tierName - Rank tier name (any case/format)
 * @returns {string|null} Asset path or null if not found
 */
export function getRankAsset(tierName) {
  if (!tierName) return null;
  const normalized = normalizeRankName(tierName);
  return rankAssets[normalized] || null;
}
`;
  
  fs.writeFileSync(MAPPINGS_FILE, content, 'utf8');
  console.log(`✓ Generated: ${MAPPINGS_FILE}`);
  console.log(`  - ${Object.keys(rankMappings).length} rank mappings`);
}

// Main execution
async function main() {
  console.log('🎮 Valorant Rank Icon Downloader');
  console.log('================================\n');
  
  // Ensure directory exists
  ensureDir(RANKS_DIR);
  
  try {
    // Download rank icons
    const rankMappings = await downloadRanks();
    
    // Generate mappings file
    generateMappingsFile(rankMappings);
    
    console.log('\n✅ Rank icon download complete!\n');
    console.log('Next steps:');
    console.log('  1. Icons are saved to: public/ranks/');
    console.log('  2. Mappings generated: lib/rankMappings.js');
    console.log('  3. Use <RankIcon tierName="Gold 3" /> in components\n');
    
  } catch (err) {
    console.error('\n❌ Rank download failed:', err);
    process.exit(1);
  }
}

// Run the script
main();
